### ISSUE TITLE
Would this work for OneNote?

### ISSUE THREAD

**Issue by SiTox** [stephenegriffin/SampleNativeCOMAddin#1]
Sorry if this might seemed to be offtopic, but I'm looking for a native add-in for OneNote. Currently, I'm stuck and can't find a working example that would do simple COM connection and output a message box

**Comment by stephenegriffin** [comment]
Probably not. I’d start here: https://github.com/topics/onenote-addin

**Comment by SiTox** [comment]
Again sorry to bother you, but I've dug thru out the whole internet and couldn't find any example of C++ OneNote addin code. I'm doing some small pet project for myself, and you seemed to understand how the office COM thing works, maybe you can help me?

**Comment by stephenegriffin** [comment]
Best I can do is point you at the old docs: https://docs.microsoft.com/en-us/previous-versions/office/gg649853(v=office.14)

I don't know anything about add-ins for OneNote.
